---
title: "Covid Compare analysis"
output:
  html_notebook:
    code_folding: hide
    theme: lumen
    toc: true
    toc_float: true
---

```{r message=FALSE, warning=FALSE}
source("covidcomp_lib.R")
```

# Total counts and days to double

```{r message=FALSE, warning=FALSE}
joined <- readJoinJhuData()
comp_data <- joined %>% genCompData()
comp_data %>% plotComps()
```

# Demographics

```{r}
join_country <- function(df, join_data, by=c("Country/Region"="country")) {
  df %>% left_join(
    join_data %>%
      mutate(country = case_when(
        grepl("Bahamas", country) ~ "The Bahamas",
        grepl("Gambia", country) ~ "Gambia, The",
        grepl("Czech", country) ~ "Czechia",
        grepl("Iran", country) ~ "Iran",
        grepl("Ivoire", country) ~ "Cote d'Ivoire",
        grepl("Brunei", country) ~ "Brunei",
        grepl("Republic of Korea", country) ~ "Korea, South",
        grepl("Korea, Rep.", country) ~ "Korea, South",
        grepl("United Kingdom of", country) ~ "United Kingdom",
        grepl("United States", country) ~ "US",
        grepl("Viet", country) ~ "Vietnam",
        grepl("Russia", country) ~ "Russia",
        grepl("Bolivia", country) ~ "Bolivia",
        grepl("Venezuela", country) ~ "Venezuela",
        grepl("Tanzania", country) ~ "Tanzania",
        grepl("Macedonia", country) ~ "North Macedonia",
        grepl("Moldova", country) ~ "Moldova",
        grepl("Egypt", country) ~ "Egypt",
        grepl("Kyrgyz", country) ~ "Kyrgyzstan",
        grepl("Slovak", country) ~ "Slovakia",
        grepl("Vincent", country) ~ "Saint Vincent and the Grenadines",
        grepl("Lucia", country) ~ "Saint Lucia",
        grepl("Martin", country) ~ "Martinique",
        # careful with Congo
        country == "Democratic Republic of the Congo" |
          country == "Congo, Dem. Rep." ~ "Congo (Kinshasa)",
        country == "Congo" | country == "Congo, Rep." ~ "Congo (Brazzaville)",
        TRUE ~ country)),
    by = by)
}
```

## World bank population data

World bank data looks best.  Only two years old.

```{r}
library(wbstats)
demo_data <- joined %>%
  group_by(`Country/Region`) %>%
  summarise_at(vars(confirmed, deaths, recovered), max) %>%
  join_country(
    wb(indicator = "SP.POP.TOTL", startdate = 2018, enddate = 2018) %>%
      rename(population = value) %>%
      select(country, population)) %>%
  mutate(population = case_when(
    `Country/Region` == "Taiwan*" ~ 23780452,
    `Country/Region` == "Cruise Ship" ~ 3711,
    TRUE ~ population)) %>%
  join_country(
    wb(indicator = "SP.POP.65UP.TO.ZS", startdate = 2018, enddate = 2018) %>%
      rename(pct_over_65 = value) %>%
      select(country, pct_over_65)) %>%
  mutate(confirmed_pct = confirmed * 100 / population,
         deaths_pct = deaths * 100 / population,
         recovered_pct = recovered * 100 / population) %>%
  ungroup()

demo_data %>% arrange(desc(deaths_pct), desc(deaths))

demo_data %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(confirmed_pct, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(confirmed_pct, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique",
                                  "Italy")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)


demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2) +
  theme(legend.position = "none")
```

# US State-level

```{r}
state_comp_data <- joined %>%
  filter(`Country/Region` == "US") %>%
  filter(!grepl(",", `Province/State`)) %>%
  genCompData(geo_level = "Province/State", min_total = 2)
state_comp_data %>% plotComps()
```

## US State testing
```{r}
library(rvest)
library(magrittr)
test_html <- read_html("https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#")

state_tests <- test_html %>% html_nodes(".waffle") %>% extract2(4) %>%
  html_table() %>% set_colnames(
    c("row", "date", "state", "positive", "negative", "pending", "deaths",
      "total tests")) %>%
  filter(!row_number() %in% 1:2) %>% select(-row) %>%
  mutate_at(vars(date), ymd) %>%
  mutate_at(vars(-date, -state), ~ gsub(",", "", .)) %>%
  mutate_at(vars(-date, -state), as.numeric)
```

```{r fig.height=24, fig.width=7}
state_tests %>%
  gather(stat, value, -date, -state) %>%
  ggplot(aes(date, value, color = stat)) +
  geom_line() +
  facet_grid(vars(state), vars(stat), scales = "free_y")
```