---
title: "Covid Compare analysis"
output:
  html_notebook:
    code_folding: hide
    theme: lumen
    toc: true
    toc_float: true
---

# Total counts and days to double

```{r message=FALSE, warning=FALSE}
source("../covidcomp_lib.R")
joined <- readJoinJhuData()
comp_data <- joined %>% genCompData()
comp_data %>% plotComps()
```

# Demographics

```{r}
join_wb_country <- function(df, join_data, by=c("Country/Region"="country")) {
  df %>% left_join(
    join_data %>%
      mutate(country = case_when(
        grepl("Bahamas", country) ~ "The Bahamas",
        grepl("Gambia", country) ~ "Gambia, The",
        grepl("Czech", country) ~ "Czechia",
        grepl("Iran", country) ~ "Iran",
        grepl("Ivoire", country) ~ "Cote d'Ivoire",
        grepl("Brunei", country) ~ "Brunei",
        grepl("Republic of Korea", country) ~ "Korea, South",
        grepl("Korea, Rep.", country) ~ "Korea, South",
        grepl("United Kingdom of", country) ~ "United Kingdom",
        grepl("United States", country) ~ "US",
        grepl("Viet", country) ~ "Vietnam",
        grepl("Russia", country) ~ "Russia",
        grepl("Bolivia", country) ~ "Bolivia",
        grepl("Venezuela", country) ~ "Venezuela",
        grepl("Tanzania", country) ~ "Tanzania",
        grepl("Macedonia", country) ~ "North Macedonia",
        grepl("Moldova", country) ~ "Moldova",
        grepl("Egypt", country) ~ "Egypt",
        grepl("Kyrgyz", country) ~ "Kyrgyzstan",
        grepl("Slovak", country) ~ "Slovakia",
        grepl("Vincent", country) ~ "Saint Vincent and the Grenadines",
        grepl("Lucia", country) ~ "Saint Lucia",
        grepl("Martin", country) ~ "Martinique",
        # careful with Congo
        country == "Democratic Republic of the Congo" |
          country == "Congo, Dem. Rep." ~ "Congo (Kinshasa)",
        country == "Congo" | country == "Congo, Rep." ~ "Congo (Brazzaville)",
        TRUE ~ country)),
    by = by)
}
```

## World bank population data

World bank data looks best.  Only two years old.

```{r}
library(wbstats)
demo_data <- joined %>%
  group_by(`Country/Region`) %>%
  summarise_at(vars(confirmed, deaths, recovered), max) %>%
  join_country(
    wb(indicator = "SP.POP.TOTL", startdate = 2018, enddate = 2018) %>%
      rename(population = value) %>%
      select(country, population)) %>%
  mutate(population = case_when(
    `Country/Region` == "Taiwan*" ~ 23780452,
    `Country/Region` == "Cruise Ship" ~ 3711,
    TRUE ~ population)) %>%
  join_country(
    wb(indicator = "SP.POP.65UP.TO.ZS", startdate = 2018, enddate = 2018) %>%
      rename(pct_over_65 = value) %>%
      select(country, pct_over_65)) %>%
  mutate(confirmed_pct = confirmed * 100 / population,
         deaths_pct = deaths * 100 / population,
         recovered_pct = recovered * 100 / population) %>%
  ungroup()

demo_data %>% arrange(desc(deaths_pct), desc(deaths))

demo_data %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(confirmed_pct, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(confirmed_pct, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)

demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique",
                                  "Italy")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  head(15) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2)


demo_data %>%
  filter(!`Country/Region` %in% c("Cruise Ship", "San Marino", "Martinique")) %>%
  arrange(desc(deaths_pct), desc(deaths)) %>%
  mutate(`Country/Region` = reorder(`Country/Region`, desc(deaths_pct))) %>%
  ggplot(aes(pct_over_65, deaths_pct)) +
  geom_point(aes(color = `Country/Region`)) +
  geom_line(stat = "smooth", method = "lm", alpha = 0.2) +
  theme(legend.position = "none")
```

# US State-level

```{r}
library(covid19us)
get_states_daily()

state_comp_data <- state_data %>%
  genCompData(geo_level = "Province/State", min_total = 2)
state_comp_data %>% plotComps()
```

## US State testing

```{r}
#library(rvest)
#library(magrittr)
#library(jsonlite)

(state_tests <- url("https://covidtracking.com/api/states/daily") %>%
  jsonlite::fromJSON() %>%
  mutate_at(vars(date), ymd))
```

```{r fig.height=20, fig.width=7}
state_tests %>% select(-total) %>%
  group_by(state) %>%
  summarise(
    positive_test_rate = sum(positive)/((sum(positive) + sum(negative)))) %>%
  arrange(desc(positive_test_rate))

state_tests %>% select(-total) %>%
  group_by(state) %>%
  gather(stat, value, -date, -state)  %>%
  mutate_at(vars(value), as.numeric) %>%
  ggplot(aes(date, value, fill = stat)) +
  geom_bar(stat = "identity") +
  facet_grid(vars(state), scales = "free_y")
```


```{r}
states <- state_data %>%
  left_join(state_abb_map, by = c("Province/State" = "name")) %>%
  left_join(state_tests %>%
              rename_at(vars(-date, -state), list(~ paste0(., "_tests"))),
            by = c("abb" = "state", "date"))
```


```{r fig.height=20, message=FALSE, warning=FALSE}
source("../covidcomp_lib.R")
states %>% select(-abb, -dateChecked_tests) %>%
  genCompData(geo_level = "Province/State", min_total = 2) %>%
  plotComps(min_total = 2, smooth_plots = TRUE, scale_to_fit = TRUE)
```

```{r}
jhu <- fetchPrepJhuData()
```

```{r}
source("../covidcomp_lib.R")
p <- fetchPrepJhuData() %>%
  genCompData() %>% 
  filter(location != "San Marino") %>%
  plotComps()
suppressWarnings(print(p))
```

```{r}
```

```{r}
source("../covidcomp_lib.R")
covtrack <- fetchPrepCovTrackData()
```
```{r}
p <- covtrack %>% genCompData(geo_level = "state", min_stat = "death", min_thresh = 1) %>%
  plotComps()

suppressWarnings(print(p))
```

# Corona Data Scraper project
```{r}
library(jsonlite)
cds_data <- jsonlite::fromJSON("https://coronadatascraper.com/timeseries-byLocation.json")
names(cds_data)
```

```{r}
library(tidyverse)
ita <- cds_data[["ITA"]]
names(ita)
```

```{r}
cds_data %>% head(2)
```
```{r}
sapply(cds_data, "[[", "dates") %>% unlist() %>% names() %>% gsub("^.*\\.", "", .) %>% table() 
sapply(cds_data, names) %>% unlist %>% table %>% sort
```

```{r}
library(tidyverse)
library(jsonlite)
library(lubridate)

cds_data <- jsonlite::fromJSON(
  "https://coronadatascraper.com/timeseries-byLocation.json")

valueOrNA <- function(x) {
  ifelse(!is.null(x), x, NA)
}

getTsMax <- function(cds_loc, metric) {
  suppressWarnings(max(as.numeric(sapply(
    Filter(function(y) {!is.null(y[[metric]])}, cds_loc$dates), "[[", metric))))
}

names(cds_data) %>%
  lapply(FUN = function(x) {
    list(
      name = x,
      country = valueOrNA(cds_data[[x]]$country),
      aggregate = valueOrNA(cds_data[[x]]$aggregate),
      state = valueOrNA(cds_data[[x]]$state),
      population = valueOrNA(cds_data[[x]]$population),
      county = valueOrNA(cds_data[[x]]$county),
      city = valueOrNA(cds_data[[x]]$city),
      max_deaths = getTsMax(cds_data[[x]], "deaths"),
      max_cases = getTsMax(cds_data[[x]], "cases"),
      max_tested = getTsMax(cds_data[[x]], "tested"),
      max_active = getTsMax(cds_data[[x]], "active"),
      max_recovered = getTsMax(cds_data[[x]], "recovered"),
      # deaths_ts = lapply(names(cds_data[[x]]$dates), FUN = function(x) {
      #   c(x = valueOrNA(cds_data[[x]]$dates[[x]]$deaths))
      # }),
      date = list(names(cds_data[[x]]$dates)),
      ts_values = list(cds_data[[x]]$dates))
    }) %>%
  bind_rows() %>% 
  mutate(
    max_deaths = na_if(max_deaths, -Inf),
    max_cases = na_if(max_cases, -Inf),
    max_tested = na_if(max_tested, -Inf),
    max_active = na_if(max_active, -Inf),
    max_recovered = na_if(max_recovered, -Inf)) %>%
  mutate(
    max_deaths_per_capita = max_deaths / population * 1e6,
    max_tested_per_capita = max_tested / population * 1e6,
    max_recovered_per_capita = max_recovered / population * 1e6,
    max_positive_test_rate = max_cases / max_tested) %>%
  unnest(c(date, ts_values)) %>%
  mutate(
    date = ymd(date),
    deaths = unlist(sapply(ts_values, FUN = function(x) {
      return(valueOrNA(x$deaths)) })),
    active = unlist(sapply(ts_values, FUN = function(x) {
      return(valueOrNA(x$active)) })),
    cases = unlist(sapply(ts_values, FUN = function(x) {
      return(valueOrNA(x$cases)) })),
    recovered = unlist(sapply(ts_values, FUN = function(x) {
      return(valueOrNA(x$recovered)) })),
    tested = unlist(sapply(ts_values, FUN = function(x) {
      return(valueOrNA(x$tested)) })),
    growthFactor = unlist(sapply(ts_values, FUN = function(x) {
      return(valueOrNA(x$growthFactor)) })),
    cfr = deaths / cases,
    ptr = cases / tested,
    rr = recovered / cases
    ) %>%
  select(-ts_values) %>%
  gather(stat, value, deaths, active, cases, recovered, tested,
         growthFactor, cfr, ptr, rr) %>%
  mutate(popM = value / population * 1e6) -> cds
```

# NYT data

```{r}
read_csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")) %>%
  mutate(cfr = deaths / cases, county = paste(county, "County")) %>%
  mutate(state = unlist(sapply(state, FUN = function(x) { unlist(valueOrNA(state.abb[which(state.name == x)])) }))) %>%
  gather(stat, total, cases, deaths, cfr) %>%
  select(-fips) %>%
  unite(county, county, state, sep = ", ") %>%
  mutate(county = paste0(county, ", USA")) %>%
  left_join(cds %>% filter(country == "USA" & aggregate == "county") %>% select(name, population) %>% unique(), by = c("county" = "name")) %>%
  mutate(popM = total / population * 1e6) %>%
  group_by(county) %>%
  mutate(max_deaths = max(total[stat == "deaths"], na.rm = TRUE)) %>%
  ungroup() %>%
  filter(max_deaths >= 5) %>%
  genPlotComps(geo_level = "county")
```

# Fluview

```{r}
library(cdcfluview)
```

```{r}
get_flu_data()
```

```{r}
pi_mortality()
```

